#!/bin/bash

ARMA2ASCII_BIN=../../src/arma2ascii
BMDCA_BIN=../../src/bmdca
BMDCA_SAMPLE_BIN=../../src/bmdca_sample
NUMERIC2FASTA_BIN=../../src/numeric2fasta
PROCESS_MSA_BIN=../../src/process_msa

EXAMPLE_DIR=../../example/
EXAMPLE_BMDCA_CONF=../../example/bmdca.conf
EXAMPLE_BMDCA_SAMPLE_CONF=../../example/bmdca_sample.conf
EXAMPLE_MSA=../../example/PF00014_full.fasta

function check_dependencies {
  if [ -f ${ARMA2ASCII_BIN} ] && [ -f "${BMDCA_BIN}" ] && [ -f "${BMDCA_SAMPLE_BIN}" ] && [ -f "${NUMERIC2FASTA_BIN}" ] && [ -f "${PROCESS_MSA_BIN}" ]; then
    :
  else
    echo "Build bmDCA before running any tests." >&2
    exit 1
  fi
  if [ -d "${EXAMPLE_DIR}" ] && [ -f "${EXAMPLE_BMDCA_SAMPLE_CONF}" ] && [ -f "${EXAMPLE_BMDCA_CONF}" ] && [ -f "${EXAMPLE_MSA}" ]; then
    :
  else
    echo "Config files in example/ are missing..." >&2
    exit 1
  fi
}
